git:
  changelog: 'npx auto-changelog --stdout --commit-limit false -u --template https://raw.githubusercontent.com/release-it/release-it/master/templates/changelog-compact.hbs'
  push: false
  tag: true
  commit: true
  tagName: v${version}
  commitMessage: 'chore: release v${version}'
github:
  release: false
hooks:
  after:bump: 'npx auto-changelog -v ${version}'
npm:
  publish: false
  skipChecks: true
