blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/RobBrazier/svelte-awesome/discussions
    about: Please ask and answer questions here - only using Issues for bugs/feature requests.
